if(EXISTS "/home/ppsome/project/bustub/build_rel/test/b_plus_tree_tombstone_test[1]_tests.cmake")
  include("/home/ppsome/project/bustub/build_rel/test/b_plus_tree_tombstone_test[1]_tests.cmake")
else()
  add_test(b_plus_tree_tombstone_test_NOT_BUILT b_plus_tree_tombstone_test_NOT_BUILT)
endif()
