if(EXISTS "/home/ppsome/project/bustub/build_rel/test/disk_manager_test[1]_tests.cmake")
  include("/home/ppsome/project/bustub/build_rel/test/disk_manager_test[1]_tests.cmake")
else()
  add_test(disk_manager_test_NOT_BUILT disk_manager_test_NOT_BUILT)
endif()
