if(EXISTS "/home/ppsome/project/bustub/build_rel/test/hyperloglog_test[1]_tests.cmake")
  include("/home/ppsome/project/bustub/build_rel/test/hyperloglog_test[1]_tests.cmake")
else()
  add_test(hyperloglog_test_NOT_BUILT hyperloglog_test_NOT_BUILT)
endif()
